### ISSUE TITLE
Homepage loads slowly

### ISSUE THREAD

**Issue by marcelm** [ScilifelabDataCentre/data.scilifelab.se#247]
On first load (with cold caches), 14 MB need to be transferred before https://datacentre.scilifelab.se/ is fully loaded. This is noticable even on a fast connection. This is due to unscaled images such as https://data.scilifelab.se/img/service_thumbnails/portal.jpg, which has a size of 5000x2500 pixels, but is only shown at 278x139 pixels.

**Comment by senthil10** [comment]
Hello @marcelm ,

A big thank you for bring it to our notice, we have now [optimised our images](https://github.com/ScilifelabDataCentre/data.scilifelab.se/pull/252) and reduced the load transfer by 80%. 

Will now resolve this issue.

**Comment by marcelm** [comment]
Nice, thanks a lot! The updates seem not to be deployed, yet, so I’ll check it out later.

**Comment by senthil10** [comment]
Ah yes, it was not deployed then, but it is now.

**Comment by marcelm** [comment]
It loads instantly now :smile:
